# Generated by Django 3.2.4 on 2021-07-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsvn_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vi_Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vi_text', models.CharField(default='', max_length=200)),
                ('ja_text', models.CharField(default='', max_length=200)),
                ('hiragana_text', models.CharField(default='', max_length=200)),
                ('katakana_text', models.CharField(default='', max_length=200)),
                ('description', models.CharField(max_length=100)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
