# Generated by Django 3.2.4 on 2021-07-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsvn_dictionary', '0002_vi_dictionary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vi_dictionary',
            old_name='ja_text',
            new_name='kanji_text',
        ),
    ]
