# Generated by Django 3.2.4 on 2021-07-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsvn_dictionary', '0004_remove_vi_dictionary_katakana_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='vi_dictionary',
            name='katakana_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
